### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by GorlikItsMe** [bogdal/gusregon#17]
```
PS C:\project> pip install gusregon
Collecting gusregon
  Using cached https://files.pythonhosted.org/packages/6f/71/c68fc0e7034b1abc33814cc488fb9ddbd95a920ce322605814a08f737799/gusregon-1.1.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-wm62h1su\\gusregon\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-wm62h1su\\gusregon\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-install-wm62h1su\gusregon\pip-egg-info'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-wm62h1su\gusregon\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-wm62h1su\gusregon\setup.py", line 34, in <module>
        long_description=open('README.rst').read(),
      File "c:\users\user\appdata\local\programs\python\python38-32\lib\encodings\cp1250.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1083: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by GorlikItsMe** [comment]
This fix problems https://github.com/bogdal/gusregon/pull/15
